version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: userdb
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"             # host:3307 -> container:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks: [mynet]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
    ports:
      - "8080:80"
    depends_on: [mysql]
    networks: [mynet]

  app:                          # ex-php72 : conteneur Apache+PHP 7.2
    build: ./php72
    volumes:
      - ./src:/var/www/html:cached
      - /var/www/html/storage               # laissé au conteneur (rapide)
      - /var/www/html/bootstrap/cache
    depends_on: [mysql]
    networks: [mynet]

  nginx:
    image: nginx:alpine
    container_name: docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:cached
    depends_on: [app]
    networks: [mynet]

networks:
  mynet:
    driver: bridge
